on: [push, pull_request]
name: Memcache Installation test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Enable CGO
        run: echo CGO_ENABLED=1 >> ${GITHUB_ENV}
      - name: Enable Go Modules
        run: echo GO111MODULE=on >> ${GITHUB_ENV}
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: Install Memcache
        run: bash ${GITHUB_WORKSPACE}/install.sh
      - name: Test package
        run: memcache --help
